import type { TalentId } from "../data/types";

export type TalentBranch = "survival" | "offense" | "efficiency";
export type TalentFragmentKind = "basic" | "elite";
export type TalentEffectKind =
  | "maxHpAdd"
  | "iframeAdd"
  | "speedMul"
  | "pickupRadiusMul"
  | "damageAdd"
  | "critAdd"
  | "periodMul"
  | "projectileSpeedMul"
  | "pierceAdd"
  | "projectilesAdd"
  | "pointRewardMul"
  | "fragmentRewardMul"
  | "skillPointsAdd";

export interface TalentLevelDef {
  pointCost: number;
  fragmentCost: number;
  bonus: number;
}

export interface TalentNodeDef {
  id: TalentId;
  branch: TalentBranch;
  name: string;
  description: string;
  fragmentKind: TalentFragmentKind;
  effectKind: TalentEffectKind;
  levels: TalentLevelDef[];
  requires?: { id: TalentId; level: number };
  isCore?: boolean;
}

export const TALENT_NODES: Record<TalentId, TalentNodeDef> = {
  // ── SURVIVAL branch ────────────────────────────────────────────────────────
  // Basic nodes (18)
  survivalVitality: {
    id: "survivalVitality",
    branch: "survival",
    name: "Vitality Matrix",
    description: "Increase starting max HP.",
    fragmentKind: "basic",
    effectKind: "maxHpAdd",
    levels: [
      { pointCost: 120, fragmentCost: 10, bonus: 2 },
      { pointCost: 180, fragmentCost: 16, bonus: 2 },
      { pointCost: 250, fragmentCost: 24, bonus: 2 },
      { pointCost: 320, fragmentCost: 32, bonus: 2 },
      { pointCost: 420, fragmentCost: 40, bonus: 2 },
    ],
  },
  survivalPhase: {
    id: "survivalPhase",
    branch: "survival",
    name: "Phase Shell",
    description: "Gain extra hit-invulnerability time.",
    fragmentKind: "elite",
    effectKind: "iframeAdd",
    requires: { id: "survivalVitality", level: 2 },
    levels: [
      { pointCost: 140, fragmentCost: 2, bonus: 0.04 },
      { pointCost: 220, fragmentCost: 3, bonus: 0.04 },
      { pointCost: 320, fragmentCost: 4, bonus: 0.04 },
      { pointCost: 420, fragmentCost: 5, bonus: 0.04 },
    ],
  },
  survivalHp2: {
    id: "survivalHp2",
    branch: "survival",
    name: "Cell Density I",
    description: "Increase starting max HP.",
    fragmentKind: "basic",
    effectKind: "maxHpAdd",
    levels: [
      { pointCost: 100, fragmentCost: 8, bonus: 1 },
      { pointCost: 160, fragmentCost: 14, bonus: 1 },
      { pointCost: 230, fragmentCost: 20, bonus: 1 },
      { pointCost: 300, fragmentCost: 28, bonus: 1 },
    ],
  },
  survivalHp3: {
    id: "survivalHp3",
    branch: "survival",
    name: "Cell Density II",
    description: "Increase starting max HP.",
    fragmentKind: "basic",
    effectKind: "maxHpAdd",
    requires: { id: "survivalHp2", level: 2 },
    levels: [
      { pointCost: 150, fragmentCost: 12, bonus: 1 },
      { pointCost: 220, fragmentCost: 18, bonus: 1 },
      { pointCost: 300, fragmentCost: 26, bonus: 1 },
      { pointCost: 380, fragmentCost: 34, bonus: 1 },
    ],
  },
  survivalHp4: {
    id: "survivalHp4",
    branch: "survival",
    name: "Cell Density III",
    description: "Increase starting max HP.",
    fragmentKind: "basic",
    effectKind: "maxHpAdd",
    requires: { id: "survivalHp3", level: 2 },
    levels: [
      { pointCost: 200, fragmentCost: 16, bonus: 1 },
      { pointCost: 280, fragmentCost: 22, bonus: 1 },
      { pointCost: 360, fragmentCost: 30, bonus: 1 },
    ],
  },
  survivalHp5: {
    id: "survivalHp5",
    branch: "survival",
    name: "Cell Density IV",
    description: "Increase starting max HP.",
    fragmentKind: "basic",
    effectKind: "maxHpAdd",
    requires: { id: "survivalVitality", level: 3 },
    levels: [
      { pointCost: 250, fragmentCost: 20, bonus: 2 },
      { pointCost: 350, fragmentCost: 28, bonus: 2 },
      { pointCost: 460, fragmentCost: 38, bonus: 2 },
    ],
  },
  survivalHp6: {
    id: "survivalHp6",
    branch: "survival",
    name: "Cell Density V",
    description: "Increase starting max HP.",
    fragmentKind: "basic",
    effectKind: "maxHpAdd",
    requires: { id: "survivalHp5", level: 2 },
    levels: [
      { pointCost: 300, fragmentCost: 24, bonus: 2 },
      { pointCost: 400, fragmentCost: 34, bonus: 2 },
      { pointCost: 520, fragmentCost: 44, bonus: 2 },
    ],
  },
  survivalIframe2: {
    id: "survivalIframe2",
    branch: "survival",
    name: "Phase Shell II",
    description: "Gain extra hit-invulnerability time.",
    fragmentKind: "elite",
    effectKind: "iframeAdd",
    requires: { id: "survivalPhase", level: 2 },
    levels: [
      { pointCost: 180, fragmentCost: 3, bonus: 0.02 },
      { pointCost: 260, fragmentCost: 4, bonus: 0.02 },
      { pointCost: 360, fragmentCost: 5, bonus: 0.02 },
    ],
  },
  survivalIframe3: {
    id: "survivalIframe3",
    branch: "survival",
    name: "Phase Shell III",
    description: "Gain extra hit-invulnerability time.",
    fragmentKind: "elite",
    effectKind: "iframeAdd",
    requires: { id: "survivalIframe2", level: 2 },
    levels: [
      { pointCost: 220, fragmentCost: 4, bonus: 0.02 },
      { pointCost: 310, fragmentCost: 5, bonus: 0.02 },
      { pointCost: 420, fragmentCost: 6, bonus: 0.02 },
    ],
  },
  survivalIframe4: {
    id: "survivalIframe4",
    branch: "survival",
    name: "Phase Shell IV",
    description: "Gain extra hit-invulnerability time.",
    fragmentKind: "elite",
    effectKind: "iframeAdd",
    requires: { id: "survivalIframe3", level: 2 },
    levels: [
      { pointCost: 280, fragmentCost: 5, bonus: 0.02 },
      { pointCost: 380, fragmentCost: 6, bonus: 0.02 },
    ],
  },
  survivalSpeed1: {
    id: "survivalSpeed1",
    branch: "survival",
    name: "Kinetic Drive I",
    description: "Increase movement speed.",
    fragmentKind: "basic",
    effectKind: "speedMul",
    levels: [
      { pointCost: 110, fragmentCost: 9, bonus: 0.02 },
      { pointCost: 170, fragmentCost: 15, bonus: 0.02 },
      { pointCost: 240, fragmentCost: 22, bonus: 0.02 },
      { pointCost: 320, fragmentCost: 30, bonus: 0.02 },
    ],
  },
  survivalSpeed2: {
    id: "survivalSpeed2",
    branch: "survival",
    name: "Kinetic Drive II",
    description: "Increase movement speed.",
    fragmentKind: "basic",
    effectKind: "speedMul",
    requires: { id: "survivalSpeed1", level: 2 },
    levels: [
      { pointCost: 160, fragmentCost: 13, bonus: 0.02 },
      { pointCost: 230, fragmentCost: 19, bonus: 0.02 },
      { pointCost: 310, fragmentCost: 27, bonus: 0.02 },
    ],
  },
  survivalSpeed3: {
    id: "survivalSpeed3",
    branch: "survival",
    name: "Kinetic Drive III",
    description: "Increase movement speed.",
    fragmentKind: "basic",
    effectKind: "speedMul",
    requires: { id: "survivalSpeed2", level: 2 },
    levels: [
      { pointCost: 210, fragmentCost: 17, bonus: 0.02 },
      { pointCost: 290, fragmentCost: 23, bonus: 0.02 },
      { pointCost: 380, fragmentCost: 31, bonus: 0.02 },
    ],
  },
  survivalSpeed4: {
    id: "survivalSpeed4",
    branch: "survival",
    name: "Kinetic Drive IV",
    description: "Increase movement speed.",
    fragmentKind: "basic",
    effectKind: "speedMul",
    requires: { id: "survivalSpeed3", level: 2 },
    levels: [
      { pointCost: 270, fragmentCost: 21, bonus: 0.02 },
      { pointCost: 360, fragmentCost: 28, bonus: 0.02 },
    ],
  },
  survivalPickup1: {
    id: "survivalPickup1",
    branch: "survival",
    name: "Gravity Lens I",
    description: "Increase pickup collection radius.",
    fragmentKind: "basic",
    effectKind: "pickupRadiusMul",
    levels: [
      { pointCost: 100, fragmentCost: 8, bonus: 0.05 },
      { pointCost: 160, fragmentCost: 14, bonus: 0.05 },
      { pointCost: 230, fragmentCost: 21, bonus: 0.05 },
      { pointCost: 310, fragmentCost: 29, bonus: 0.05 },
    ],
  },
  survivalPickup2: {
    id: "survivalPickup2",
    branch: "survival",
    name: "Gravity Lens II",
    description: "Increase pickup collection radius.",
    fragmentKind: "basic",
    effectKind: "pickupRadiusMul",
    requires: { id: "survivalPickup1", level: 2 },
    levels: [
      { pointCost: 150, fragmentCost: 12, bonus: 0.05 },
      { pointCost: 220, fragmentCost: 18, bonus: 0.05 },
      { pointCost: 300, fragmentCost: 26, bonus: 0.05 },
    ],
  },
  survivalPickup3: {
    id: "survivalPickup3",
    branch: "survival",
    name: "Gravity Lens III",
    description: "Increase pickup collection radius.",
    fragmentKind: "basic",
    effectKind: "pickupRadiusMul",
    requires: { id: "survivalPickup2", level: 2 },
    levels: [
      { pointCost: 200, fragmentCost: 16, bonus: 0.05 },
      { pointCost: 280, fragmentCost: 22, bonus: 0.05 },
      { pointCost: 370, fragmentCost: 30, bonus: 0.05 },
    ],
  },
  survivalPickup4: {
    id: "survivalPickup4",
    branch: "survival",
    name: "Gravity Lens IV",
    description: "Increase pickup collection radius.",
    fragmentKind: "basic",
    effectKind: "pickupRadiusMul",
    requires: { id: "survivalPickup3", level: 2 },
    levels: [
      { pointCost: 260, fragmentCost: 20, bonus: 0.05 },
      { pointCost: 350, fragmentCost: 28, bonus: 0.05 },
    ],
  },
  // Core nodes (6)
  survivalCoreHp1: {
    id: "survivalCoreHp1",
    branch: "survival",
    name: "Bastion Protocol I",
    description: "Large increase to starting max HP.",
    fragmentKind: "elite",
    effectKind: "maxHpAdd",
    requires: { id: "survivalVitality", level: 3 },
    isCore: true,
    levels: [
      { pointCost: 700, fragmentCost: 5, bonus: 3 },
      { pointCost: 1000, fragmentCost: 7, bonus: 3 },
    ],
  },
  survivalCoreHp2: {
    id: "survivalCoreHp2",
    branch: "survival",
    name: "Bastion Protocol II",
    description: "Large increase to starting max HP.",
    fragmentKind: "elite",
    effectKind: "maxHpAdd",
    requires: { id: "survivalCoreHp1", level: 1 },
    isCore: true,
    levels: [
      { pointCost: 800, fragmentCost: 6, bonus: 3 },
      { pointCost: 1100, fragmentCost: 8, bonus: 3 },
    ],
  },
  survivalCoreHp3: {
    id: "survivalCoreHp3",
    branch: "survival",
    name: "Fortress Core",
    description: "Massive increase to starting max HP.",
    fragmentKind: "elite",
    effectKind: "maxHpAdd",
    requires: { id: "survivalCoreHp2", level: 1 },
    isCore: true,
    levels: [
      { pointCost: 1200, fragmentCost: 8, bonus: 5 },
    ],
  },
  survivalCoreIframe: {
    id: "survivalCoreIframe",
    branch: "survival",
    name: "Phase Barrier",
    description: "Significantly extend invulnerability window after a hit.",
    fragmentKind: "elite",
    effectKind: "iframeAdd",
    requires: { id: "survivalPhase", level: 3 },
    isCore: true,
    levels: [
      { pointCost: 900, fragmentCost: 7, bonus: 0.15 },
    ],
  },
  survivalCoreSpeed: {
    id: "survivalCoreSpeed",
    branch: "survival",
    name: "Overdrive Frame",
    description: "Greatly increase movement speed.",
    fragmentKind: "elite",
    effectKind: "speedMul",
    requires: { id: "survivalSpeed2", level: 2 },
    isCore: true,
    levels: [
      { pointCost: 850, fragmentCost: 6, bonus: 0.1 },
    ],
  },
  survivalCorePickup: {
    id: "survivalCorePickup",
    branch: "survival",
    name: "Void Magnet",
    description: "Greatly increase pickup collection radius.",
    fragmentKind: "elite",
    effectKind: "pickupRadiusMul",
    requires: { id: "survivalPickup2", level: 2 },
    isCore: true,
    levels: [
      { pointCost: 800, fragmentCost: 6, bonus: 0.2 },
    ],
  },

  // ── OFFENSE branch ─────────────────────────────────────────────────────────
  // Basic nodes (18)
  offenseVector: {
    id: "offenseVector",
    branch: "offense",
    name: "Vector Edge",
    description: "Increase base weapon damage.",
    fragmentKind: "basic",
    effectKind: "damageAdd",
    levels: [
      { pointCost: 120, fragmentCost: 10, bonus: 1 },
      { pointCost: 180, fragmentCost: 16, bonus: 1 },
      { pointCost: 250, fragmentCost: 24, bonus: 1 },
      { pointCost: 320, fragmentCost: 32, bonus: 1 },
      { pointCost: 420, fragmentCost: 40, bonus: 1 },
    ],
  },
  offenseCritical: {
    id: "offenseCritical",
    branch: "offense",
    name: "Critical Lens",
    description: "Increase base crit rate.",
    fragmentKind: "elite",
    effectKind: "critAdd",
    requires: { id: "offenseVector", level: 2 },
    levels: [
      { pointCost: 140, fragmentCost: 2, bonus: 0.01 },
      { pointCost: 220, fragmentCost: 3, bonus: 0.01 },
      { pointCost: 320, fragmentCost: 4, bonus: 0.01 },
      { pointCost: 420, fragmentCost: 5, bonus: 0.01 },
      { pointCost: 540, fragmentCost: 6, bonus: 0.01 },
    ],
  },
  offenseDamage2: {
    id: "offenseDamage2",
    branch: "offense",
    name: "Edge Sharpener I",
    description: "Increase base weapon damage.",
    fragmentKind: "basic",
    effectKind: "damageAdd",
    levels: [
      { pointCost: 100, fragmentCost: 8, bonus: 1 },
      { pointCost: 160, fragmentCost: 14, bonus: 1 },
      { pointCost: 230, fragmentCost: 21, bonus: 1 },
      { pointCost: 300, fragmentCost: 28, bonus: 1 },
    ],
  },
  offenseDamage3: {
    id: "offenseDamage3",
    branch: "offense",
    name: "Edge Sharpener II",
    description: "Increase base weapon damage.",
    fragmentKind: "basic",
    effectKind: "damageAdd",
    requires: { id: "offenseDamage2", level: 2 },
    levels: [
      { pointCost: 150, fragmentCost: 12, bonus: 1 },
      { pointCost: 220, fragmentCost: 18, bonus: 1 },
      { pointCost: 300, fragmentCost: 26, bonus: 1 },
    ],
  },
  offenseDamage4: {
    id: "offenseDamage4",
    branch: "offense",
    name: "Edge Sharpener III",
    description: "Increase base weapon damage.",
    fragmentKind: "basic",
    effectKind: "damageAdd",
    requires: { id: "offenseVector", level: 3 },
    levels: [
      { pointCost: 200, fragmentCost: 16, bonus: 1 },
      { pointCost: 280, fragmentCost: 22, bonus: 1 },
      { pointCost: 370, fragmentCost: 30, bonus: 1 },
    ],
  },
  offenseDamage5: {
    id: "offenseDamage5",
    branch: "offense",
    name: "Edge Sharpener IV",
    description: "Increase base weapon damage.",
    fragmentKind: "basic",
    effectKind: "damageAdd",
    requires: { id: "offenseDamage4", level: 2 },
    levels: [
      { pointCost: 260, fragmentCost: 20, bonus: 1 },
      { pointCost: 350, fragmentCost: 28, bonus: 1 },
    ],
  },
  offenseDamage6: {
    id: "offenseDamage6",
    branch: "offense",
    name: "Edge Sharpener V",
    description: "Increase base weapon damage.",
    fragmentKind: "basic",
    effectKind: "damageAdd",
    requires: { id: "offenseDamage5", level: 1 },
    levels: [
      { pointCost: 320, fragmentCost: 24, bonus: 1 },
      { pointCost: 430, fragmentCost: 34, bonus: 1 },
    ],
  },
  offenseCrit2: {
    id: "offenseCrit2",
    branch: "offense",
    name: "Focal Point I",
    description: "Increase base crit rate.",
    fragmentKind: "elite",
    effectKind: "critAdd",
    levels: [
      { pointCost: 120, fragmentCost: 2, bonus: 0.02 },
      { pointCost: 190, fragmentCost: 3, bonus: 0.02 },
      { pointCost: 270, fragmentCost: 4, bonus: 0.02 },
      { pointCost: 360, fragmentCost: 5, bonus: 0.02 },
    ],
  },
  offenseCrit3: {
    id: "offenseCrit3",
    branch: "offense",
    name: "Focal Point II",
    description: "Increase base crit rate.",
    fragmentKind: "elite",
    effectKind: "critAdd",
    requires: { id: "offenseCritical", level: 3 },
    levels: [
      { pointCost: 180, fragmentCost: 3, bonus: 0.02 },
      { pointCost: 260, fragmentCost: 4, bonus: 0.02 },
      { pointCost: 360, fragmentCost: 5, bonus: 0.02 },
    ],
  },
  offenseCrit4: {
    id: "offenseCrit4",
    branch: "offense",
    name: "Focal Point III",
    description: "Increase base crit rate.",
    fragmentKind: "elite",
    effectKind: "critAdd",
    requires: { id: "offenseCrit3", level: 2 },
    levels: [
      { pointCost: 240, fragmentCost: 4, bonus: 0.02 },
      { pointCost: 340, fragmentCost: 5, bonus: 0.02 },
    ],
  },
  offensePeriod1: {
    id: "offensePeriod1",
    branch: "offense",
    name: "Rate Optimizer I",
    description: "Reduce weapon fire interval.",
    fragmentKind: "basic",
    effectKind: "periodMul",
    levels: [
      { pointCost: 110, fragmentCost: 9, bonus: -0.03 },
      { pointCost: 170, fragmentCost: 15, bonus: -0.03 },
      { pointCost: 240, fragmentCost: 22, bonus: -0.03 },
      { pointCost: 320, fragmentCost: 30, bonus: -0.03 },
    ],
  },
  offensePeriod2: {
    id: "offensePeriod2",
    branch: "offense",
    name: "Rate Optimizer II",
    description: "Reduce weapon fire interval.",
    fragmentKind: "basic",
    effectKind: "periodMul",
    requires: { id: "offensePeriod1", level: 2 },
    levels: [
      { pointCost: 160, fragmentCost: 13, bonus: -0.03 },
      { pointCost: 230, fragmentCost: 19, bonus: -0.03 },
      { pointCost: 310, fragmentCost: 27, bonus: -0.03 },
    ],
  },
  offensePeriod3: {
    id: "offensePeriod3",
    branch: "offense",
    name: "Rate Optimizer III",
    description: "Reduce weapon fire interval.",
    fragmentKind: "basic",
    effectKind: "periodMul",
    requires: { id: "offensePeriod2", level: 2 },
    levels: [
      { pointCost: 210, fragmentCost: 17, bonus: -0.03 },
      { pointCost: 300, fragmentCost: 23, bonus: -0.03 },
    ],
  },
  offensePeriod4: {
    id: "offensePeriod4",
    branch: "offense",
    name: "Rate Optimizer IV",
    description: "Reduce weapon fire interval.",
    fragmentKind: "basic",
    effectKind: "periodMul",
    requires: { id: "offensePeriod3", level: 1 },
    levels: [
      { pointCost: 270, fragmentCost: 21, bonus: -0.03 },
      { pointCost: 370, fragmentCost: 29, bonus: -0.03 },
    ],
  },
  offenseProjSpeed1: {
    id: "offenseProjSpeed1",
    branch: "offense",
    name: "Velocity Field I",
    description: "Increase projectile speed.",
    fragmentKind: "basic",
    effectKind: "projectileSpeedMul",
    levels: [
      { pointCost: 100, fragmentCost: 8, bonus: 0.05 },
      { pointCost: 160, fragmentCost: 14, bonus: 0.05 },
      { pointCost: 230, fragmentCost: 21, bonus: 0.05 },
      { pointCost: 310, fragmentCost: 29, bonus: 0.05 },
    ],
  },
  offenseProjSpeed2: {
    id: "offenseProjSpeed2",
    branch: "offense",
    name: "Velocity Field II",
    description: "Increase projectile speed.",
    fragmentKind: "basic",
    effectKind: "projectileSpeedMul",
    requires: { id: "offenseProjSpeed1", level: 2 },
    levels: [
      { pointCost: 150, fragmentCost: 12, bonus: 0.05 },
      { pointCost: 220, fragmentCost: 18, bonus: 0.05 },
      { pointCost: 300, fragmentCost: 26, bonus: 0.05 },
    ],
  },
  offenseProjSpeed3: {
    id: "offenseProjSpeed3",
    branch: "offense",
    name: "Velocity Field III",
    description: "Increase projectile speed.",
    fragmentKind: "basic",
    effectKind: "projectileSpeedMul",
    requires: { id: "offenseProjSpeed2", level: 2 },
    levels: [
      { pointCost: 200, fragmentCost: 16, bonus: 0.05 },
      { pointCost: 280, fragmentCost: 22, bonus: 0.05 },
    ],
  },
  offenseProjSpeed4: {
    id: "offenseProjSpeed4",
    branch: "offense",
    name: "Velocity Field IV",
    description: "Increase projectile speed.",
    fragmentKind: "basic",
    effectKind: "projectileSpeedMul",
    requires: { id: "offenseProjSpeed3", level: 1 },
    levels: [
      { pointCost: 260, fragmentCost: 20, bonus: 0.05 },
      { pointCost: 360, fragmentCost: 28, bonus: 0.05 },
    ],
  },
  // Core nodes (6)
  offenseCoreDamage: {
    id: "offenseCoreDamage",
    branch: "offense",
    name: "Overcharge Core",
    description: "Large increase to base weapon damage.",
    fragmentKind: "elite",
    effectKind: "damageAdd",
    requires: { id: "offenseVector", level: 3 },
    isCore: true,
    levels: [
      { pointCost: 700, fragmentCost: 5, bonus: 3 },
      { pointCost: 1000, fragmentCost: 7, bonus: 3 },
    ],
  },
  offenseCoreCrit: {
    id: "offenseCoreCrit",
    branch: "offense",
    name: "Precision Lens",
    description: "Significantly increase crit rate.",
    fragmentKind: "elite",
    effectKind: "critAdd",
    requires: { id: "offenseCritical", level: 3 },
    isCore: true,
    levels: [
      { pointCost: 800, fragmentCost: 6, bonus: 0.05 },
      { pointCost: 1100, fragmentCost: 8, bonus: 0.05 },
    ],
  },
  offenseCorePeriod: {
    id: "offenseCorePeriod",
    branch: "offense",
    name: "Rapid Cycle",
    description: "Sharply reduce weapon fire interval.",
    fragmentKind: "elite",
    effectKind: "periodMul",
    requires: { id: "offensePeriod2", level: 2 },
    isCore: true,
    levels: [
      { pointCost: 850, fragmentCost: 6, bonus: -0.1 },
    ],
  },
  offenseCoreProjSpeed: {
    id: "offenseCoreProjSpeed",
    branch: "offense",
    name: "Hyper Velocity",
    description: "Greatly increase projectile speed.",
    fragmentKind: "elite",
    effectKind: "projectileSpeedMul",
    requires: { id: "offenseProjSpeed2", level: 2 },
    isCore: true,
    levels: [
      { pointCost: 800, fragmentCost: 6, bonus: 0.15 },
    ],
  },
  offenseCoreProjectiles: {
    id: "offenseCoreProjectiles",
    branch: "offense",
    name: "Multi-Barrel Array",
    description: "Fire additional projectiles per shot.",
    fragmentKind: "elite",
    effectKind: "projectilesAdd",
    requires: { id: "offenseVector", level: 4 },
    isCore: true,
    levels: [
      { pointCost: 900, fragmentCost: 7, bonus: 1 },
      { pointCost: 1300, fragmentCost: 9, bonus: 1 },
    ],
  },
  offenseCorePierce: {
    id: "offenseCorePierce",
    branch: "offense",
    name: "Penetration Field",
    description: "Projectiles pierce through additional enemies.",
    fragmentKind: "elite",
    effectKind: "pierceAdd",
    requires: { id: "offenseProjSpeed2", level: 2 },
    isCore: true,
    levels: [
      { pointCost: 900, fragmentCost: 7, bonus: 1 },
      { pointCost: 1300, fragmentCost: 9, bonus: 1 },
    ],
  },

  // ── EFFICIENCY branch ──────────────────────────────────────────────────────
  // Basic nodes (18)
  efficiencyPoints: {
    id: "efficiencyPoints",
    branch: "efficiency",
    name: "Salvage Protocol",
    description: "Increase run points earned.",
    fragmentKind: "basic",
    effectKind: "pointRewardMul",
    levels: [
      { pointCost: 100, fragmentCost: 12, bonus: 0.04 },
      { pointCost: 160, fragmentCost: 18, bonus: 0.04 },
      { pointCost: 230, fragmentCost: 25, bonus: 0.04 },
      { pointCost: 300, fragmentCost: 33, bonus: 0.04 },
      { pointCost: 400, fragmentCost: 42, bonus: 0.04 },
    ],
  },
  efficiencyFragments: {
    id: "efficiencyFragments",
    branch: "efficiency",
    name: "Fragment Recycler",
    description: "Increase fragment gain.",
    fragmentKind: "elite",
    effectKind: "fragmentRewardMul",
    requires: { id: "efficiencyPoints", level: 2 },
    levels: [
      { pointCost: 140, fragmentCost: 2, bonus: 0.04 },
      { pointCost: 220, fragmentCost: 3, bonus: 0.04 },
      { pointCost: 320, fragmentCost: 4, bonus: 0.04 },
      { pointCost: 420, fragmentCost: 5, bonus: 0.04 },
      { pointCost: 540, fragmentCost: 6, bonus: 0.04 },
    ],
  },
  efficiencyPoints2: {
    id: "efficiencyPoints2",
    branch: "efficiency",
    name: "Salvage Protocol II",
    description: "Increase run points earned.",
    fragmentKind: "basic",
    effectKind: "pointRewardMul",
    levels: [
      { pointCost: 90, fragmentCost: 10, bonus: 0.02 },
      { pointCost: 140, fragmentCost: 16, bonus: 0.02 },
      { pointCost: 200, fragmentCost: 23, bonus: 0.02 },
      { pointCost: 270, fragmentCost: 31, bonus: 0.02 },
    ],
  },
  efficiencyPoints3: {
    id: "efficiencyPoints3",
    branch: "efficiency",
    name: "Salvage Protocol III",
    description: "Increase run points earned.",
    fragmentKind: "basic",
    effectKind: "pointRewardMul",
    requires: { id: "efficiencyPoints2", level: 2 },
    levels: [
      { pointCost: 130, fragmentCost: 14, bonus: 0.02 },
      { pointCost: 190, fragmentCost: 20, bonus: 0.02 },
      { pointCost: 260, fragmentCost: 27, bonus: 0.02 },
    ],
  },
  efficiencyPoints4: {
    id: "efficiencyPoints4",
    branch: "efficiency",
    name: "Salvage Protocol IV",
    description: "Increase run points earned.",
    fragmentKind: "basic",
    effectKind: "pointRewardMul",
    requires: { id: "efficiencyPoints", level: 3 },
    levels: [
      { pointCost: 160, fragmentCost: 17, bonus: 0.04 },
      { pointCost: 230, fragmentCost: 24, bonus: 0.04 },
      { pointCost: 310, fragmentCost: 32, bonus: 0.04 },
    ],
  },
  efficiencyPoints5: {
    id: "efficiencyPoints5",
    branch: "efficiency",
    name: "Salvage Protocol V",
    description: "Increase run points earned.",
    fragmentKind: "basic",
    effectKind: "pointRewardMul",
    requires: { id: "efficiencyPoints4", level: 2 },
    levels: [
      { pointCost: 200, fragmentCost: 21, bonus: 0.04 },
      { pointCost: 280, fragmentCost: 29, bonus: 0.04 },
    ],
  },
  efficiencyPoints6: {
    id: "efficiencyPoints6",
    branch: "efficiency",
    name: "Salvage Protocol VI",
    description: "Increase run points earned.",
    fragmentKind: "basic",
    effectKind: "pointRewardMul",
    requires: { id: "efficiencyPoints5", level: 1 },
    levels: [
      { pointCost: 250, fragmentCost: 26, bonus: 0.04 },
      { pointCost: 340, fragmentCost: 35, bonus: 0.04 },
    ],
  },
  efficiencyPoints7: {
    id: "efficiencyPoints7",
    branch: "efficiency",
    name: "Salvage Protocol VII",
    description: "Increase run points earned.",
    fragmentKind: "basic",
    effectKind: "pointRewardMul",
    requires: { id: "efficiencyPoints3", level: 2 },
    levels: [
      { pointCost: 180, fragmentCost: 19, bonus: 0.02 },
      { pointCost: 250, fragmentCost: 26, bonus: 0.02 },
    ],
  },
  efficiencyPoints8: {
    id: "efficiencyPoints8",
    branch: "efficiency",
    name: "Salvage Protocol VIII",
    description: "Increase run points earned.",
    fragmentKind: "basic",
    effectKind: "pointRewardMul",
    requires: { id: "efficiencyPoints7", level: 1 },
    levels: [
      { pointCost: 230, fragmentCost: 24, bonus: 0.02 },
      { pointCost: 320, fragmentCost: 33, bonus: 0.02 },
    ],
  },
  efficiencyFragments2: {
    id: "efficiencyFragments2",
    branch: "efficiency",
    name: "Fragment Recycler II",
    description: "Increase fragment gain.",
    fragmentKind: "elite",
    effectKind: "fragmentRewardMul",
    levels: [
      { pointCost: 120, fragmentCost: 2, bonus: 0.02 },
      { pointCost: 190, fragmentCost: 3, bonus: 0.02 },
      { pointCost: 270, fragmentCost: 4, bonus: 0.02 },
      { pointCost: 360, fragmentCost: 5, bonus: 0.02 },
    ],
  },
  efficiencyFragments3: {
    id: "efficiencyFragments3",
    branch: "efficiency",
    name: "Fragment Recycler III",
    description: "Increase fragment gain.",
    fragmentKind: "elite",
    effectKind: "fragmentRewardMul",
    requires: { id: "efficiencyFragments2", level: 2 },
    levels: [
      { pointCost: 170, fragmentCost: 3, bonus: 0.02 },
      { pointCost: 240, fragmentCost: 4, bonus: 0.02 },
      { pointCost: 330, fragmentCost: 5, bonus: 0.02 },
    ],
  },
  efficiencyFragments4: {
    id: "efficiencyFragments4",
    branch: "efficiency",
    name: "Fragment Recycler IV",
    description: "Increase fragment gain.",
    fragmentKind: "elite",
    effectKind: "fragmentRewardMul",
    requires: { id: "efficiencyFragments", level: 3 },
    levels: [
      { pointCost: 200, fragmentCost: 3, bonus: 0.04 },
      { pointCost: 280, fragmentCost: 4, bonus: 0.04 },
      { pointCost: 370, fragmentCost: 5, bonus: 0.04 },
    ],
  },
  efficiencyFragments5: {
    id: "efficiencyFragments5",
    branch: "efficiency",
    name: "Fragment Recycler V",
    description: "Increase fragment gain.",
    fragmentKind: "elite",
    effectKind: "fragmentRewardMul",
    requires: { id: "efficiencyFragments4", level: 2 },
    levels: [
      { pointCost: 250, fragmentCost: 4, bonus: 0.04 },
      { pointCost: 350, fragmentCost: 5, bonus: 0.04 },
    ],
  },
  efficiencyFragments6: {
    id: "efficiencyFragments6",
    branch: "efficiency",
    name: "Fragment Recycler VI",
    description: "Increase fragment gain.",
    fragmentKind: "elite",
    effectKind: "fragmentRewardMul",
    requires: { id: "efficiencyFragments3", level: 2 },
    levels: [
      { pointCost: 210, fragmentCost: 3, bonus: 0.02 },
      { pointCost: 300, fragmentCost: 4, bonus: 0.02 },
    ],
  },
  efficiencyFragments7: {
    id: "efficiencyFragments7",
    branch: "efficiency",
    name: "Fragment Recycler VII",
    description: "Increase fragment gain.",
    fragmentKind: "elite",
    effectKind: "fragmentRewardMul",
    requires: { id: "efficiencyFragments6", level: 1 },
    levels: [
      { pointCost: 270, fragmentCost: 4, bonus: 0.02 },
      { pointCost: 370, fragmentCost: 5, bonus: 0.02 },
    ],
  },
  efficiencyFragments8: {
    id: "efficiencyFragments8",
    branch: "efficiency",
    name: "Fragment Recycler VIII",
    description: "Increase fragment gain.",
    fragmentKind: "elite",
    effectKind: "fragmentRewardMul",
    requires: { id: "efficiencyFragments5", level: 1 },
    levels: [
      { pointCost: 300, fragmentCost: 4, bonus: 0.04 },
      { pointCost: 420, fragmentCost: 6, bonus: 0.04 },
    ],
  },
  efficiencyFragments9: {
    id: "efficiencyFragments9",
    branch: "efficiency",
    name: "Fragment Recycler IX",
    description: "Increase fragment gain.",
    fragmentKind: "elite",
    effectKind: "fragmentRewardMul",
    requires: { id: "efficiencyFragments8", level: 1 },
    levels: [
      { pointCost: 380, fragmentCost: 5, bonus: 0.04 },
      { pointCost: 520, fragmentCost: 7, bonus: 0.04 },
    ],
  },
  efficiencyPoints9: {
    id: "efficiencyPoints9",
    branch: "efficiency",
    name: "Salvage Protocol IX",
    description: "Increase run points earned.",
    fragmentKind: "basic",
    effectKind: "pointRewardMul",
    requires: { id: "efficiencyPoints8", level: 1 },
    levels: [
      { pointCost: 290, fragmentCost: 30, bonus: 0.02 },
      { pointCost: 400, fragmentCost: 41, bonus: 0.02 },
    ],
  },
  // Core nodes (6) — skill point grants
  efficiencySkillPt1: {
    id: "efficiencySkillPt1",
    branch: "efficiency",
    name: "Neural Reservoir I",
    description: "Permanently grant skill upgrade points.",
    fragmentKind: "elite",
    effectKind: "skillPointsAdd",
    requires: { id: "efficiencyPoints", level: 2 },
    isCore: true,
    levels: [
      { pointCost: 600, fragmentCost: 4, bonus: 20 },
    ],
  },
  efficiencySkillPt2: {
    id: "efficiencySkillPt2",
    branch: "efficiency",
    name: "Neural Reservoir II",
    description: "Permanently grant skill upgrade points.",
    fragmentKind: "elite",
    effectKind: "skillPointsAdd",
    requires: { id: "efficiencySkillPt1", level: 1 },
    isCore: true,
    levels: [
      { pointCost: 700, fragmentCost: 5, bonus: 20 },
    ],
  },
  efficiencySkillPt3: {
    id: "efficiencySkillPt3",
    branch: "efficiency",
    name: "Neural Reservoir III",
    description: "Permanently grant skill upgrade points.",
    fragmentKind: "elite",
    effectKind: "skillPointsAdd",
    requires: { id: "efficiencySkillPt2", level: 1 },
    isCore: true,
    levels: [
      { pointCost: 800, fragmentCost: 5, bonus: 20 },
    ],
  },
  efficiencySkillPt4: {
    id: "efficiencySkillPt4",
    branch: "efficiency",
    name: "Neural Reservoir IV",
    description: "Permanently grant skill upgrade points.",
    fragmentKind: "elite",
    effectKind: "skillPointsAdd",
    requires: { id: "efficiencySkillPt3", level: 1 },
    isCore: true,
    levels: [
      { pointCost: 900, fragmentCost: 6, bonus: 20 },
    ],
  },
  efficiencySkillPt5: {
    id: "efficiencySkillPt5",
    branch: "efficiency",
    name: "Neural Reservoir V",
    description: "Permanently grant skill upgrade points.",
    fragmentKind: "elite",
    effectKind: "skillPointsAdd",
    requires: { id: "efficiencySkillPt4", level: 1 },
    isCore: true,
    levels: [
      { pointCost: 1000, fragmentCost: 6, bonus: 20 },
    ],
  },
  efficiencySkillPt6: {
    id: "efficiencySkillPt6",
    branch: "efficiency",
    name: "Neural Reservoir VI",
    description: "Permanently grant skill upgrade points.",
    fragmentKind: "elite",
    effectKind: "skillPointsAdd",
    requires: { id: "efficiencySkillPt5", level: 1 },
    isCore: true,
    levels: [
      { pointCost: 1100, fragmentCost: 7, bonus: 20 },
    ],
  },
};

export const TALENT_BRANCH_ORDER: TalentBranch[] = [
  "survival",
  "offense",
  "efficiency",
];
